package view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 22 07:40:40 AST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorkerDraftViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WorkerDraftViewImpl() {
    }
}

