package model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 22 07:40:00 AST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorkerDraftImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        SerialNumber,
        Qid,
        Name,
        NationalityCode,
        Gender,
        SocialStatus,
        SpouseQid,
        BirthDate,
        HiringDate,
        JobNumber,
        JobName,
        ContractType,
        EducationalLevel,
        Specialization,
        BasicSalary,
        SocialAllowance,
        TransportAllowance,
        WorkNatureAllowance,
        HousingAllowance,
        OtherAllowance,
        TotalMonthlySalary,
        HousingType,
        AdditionalNotes;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SERIALNUMBER = AttributesEnum.SerialNumber.index();
    public static final int QID = AttributesEnum.Qid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int NATIONALITYCODE = AttributesEnum.NationalityCode.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int SOCIALSTATUS = AttributesEnum.SocialStatus.index();
    public static final int SPOUSEQID = AttributesEnum.SpouseQid.index();
    public static final int BIRTHDATE = AttributesEnum.BirthDate.index();
    public static final int HIRINGDATE = AttributesEnum.HiringDate.index();
    public static final int JOBNUMBER = AttributesEnum.JobNumber.index();
    public static final int JOBNAME = AttributesEnum.JobName.index();
    public static final int CONTRACTTYPE = AttributesEnum.ContractType.index();
    public static final int EDUCATIONALLEVEL = AttributesEnum.EducationalLevel.index();
    public static final int SPECIALIZATION = AttributesEnum.Specialization.index();
    public static final int BASICSALARY = AttributesEnum.BasicSalary.index();
    public static final int SOCIALALLOWANCE = AttributesEnum.SocialAllowance.index();
    public static final int TRANSPORTALLOWANCE = AttributesEnum.TransportAllowance.index();
    public static final int WORKNATUREALLOWANCE = AttributesEnum.WorkNatureAllowance.index();
    public static final int HOUSINGALLOWANCE = AttributesEnum.HousingAllowance.index();
    public static final int OTHERALLOWANCE = AttributesEnum.OtherAllowance.index();
    public static final int TOTALMONTHLYSALARY = AttributesEnum.TotalMonthlySalary.index();
    public static final int HOUSINGTYPE = AttributesEnum.HousingType.index();
    public static final int ADDITIONALNOTES = AttributesEnum.AdditionalNotes.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WorkerDraftImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public DBSequence getId() {
        return (DBSequence) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SerialNumber, using the alias name SerialNumber.
     * @return the value of SerialNumber
     */
    public BigDecimal getSerialNumber() {
        return (BigDecimal) getAttributeInternal(SERIALNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SerialNumber.
     * @param value value to set the SerialNumber
     */
    public void setSerialNumber(BigDecimal value) {
        setAttributeInternal(SERIALNUMBER, value);
    }

    /**
     * Gets the attribute value for Qid, using the alias name Qid.
     * @return the value of Qid
     */
    public Long getQid() {
        return (Long) getAttributeInternal(QID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qid.
     * @param value value to set the Qid
     */
    public void setQid(Long value) {
        setAttributeInternal(QID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for NationalityCode, using the alias name NationalityCode.
     * @return the value of NationalityCode
     */
    public Integer getNationalityCode() {
        return (Integer) getAttributeInternal(NATIONALITYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NationalityCode.
     * @param value value to set the NationalityCode
     */
    public void setNationalityCode(Integer value) {
        setAttributeInternal(NATIONALITYCODE, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for SocialStatus, using the alias name SocialStatus.
     * @return the value of SocialStatus
     */
    public String getSocialStatus() {
        return (String) getAttributeInternal(SOCIALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SocialStatus.
     * @param value value to set the SocialStatus
     */
    public void setSocialStatus(String value) {
        setAttributeInternal(SOCIALSTATUS, value);
    }

    /**
     * Gets the attribute value for SpouseQid, using the alias name SpouseQid.
     * @return the value of SpouseQid
     */
    public Long getSpouseQid() {
        return (Long) getAttributeInternal(SPOUSEQID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpouseQid.
     * @param value value to set the SpouseQid
     */
    public void setSpouseQid(Long value) {
        setAttributeInternal(SPOUSEQID, value);
    }

    /**
     * Gets the attribute value for BirthDate, using the alias name BirthDate.
     * @return the value of BirthDate
     */
    public Timestamp getBirthDate() {
        return (Timestamp) getAttributeInternal(BIRTHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BirthDate.
     * @param value value to set the BirthDate
     */
    public void setBirthDate(Timestamp value) {
        setAttributeInternal(BIRTHDATE, value);
    }

    /**
     * Gets the attribute value for HiringDate, using the alias name HiringDate.
     * @return the value of HiringDate
     */
    public Timestamp getHiringDate() {
        return (Timestamp) getAttributeInternal(HIRINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HiringDate.
     * @param value value to set the HiringDate
     */
    public void setHiringDate(Timestamp value) {
        setAttributeInternal(HIRINGDATE, value);
    }

    /**
     * Gets the attribute value for JobNumber, using the alias name JobNumber.
     * @return the value of JobNumber
     */
    public String getJobNumber() {
        return (String) getAttributeInternal(JOBNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobNumber.
     * @param value value to set the JobNumber
     */
    public void setJobNumber(String value) {
        setAttributeInternal(JOBNUMBER, value);
    }

    /**
     * Gets the attribute value for JobName, using the alias name JobName.
     * @return the value of JobName
     */
    public String getJobName() {
        return (String) getAttributeInternal(JOBNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobName.
     * @param value value to set the JobName
     */
    public void setJobName(String value) {
        setAttributeInternal(JOBNAME, value);
    }

    /**
     * Gets the attribute value for ContractType, using the alias name ContractType.
     * @return the value of ContractType
     */
    public String getContractType() {
        return (String) getAttributeInternal(CONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractType.
     * @param value value to set the ContractType
     */
    public void setContractType(String value) {
        setAttributeInternal(CONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for EducationalLevel, using the alias name EducationalLevel.
     * @return the value of EducationalLevel
     */
    public Integer getEducationalLevel() {
        return (Integer) getAttributeInternal(EDUCATIONALLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for EducationalLevel.
     * @param value value to set the EducationalLevel
     */
    public void setEducationalLevel(Integer value) {
        setAttributeInternal(EDUCATIONALLEVEL, value);
    }

    /**
     * Gets the attribute value for Specialization, using the alias name Specialization.
     * @return the value of Specialization
     */
    public String getSpecialization() {
        return (String) getAttributeInternal(SPECIALIZATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Specialization.
     * @param value value to set the Specialization
     */
    public void setSpecialization(String value) {
        setAttributeInternal(SPECIALIZATION, value);
    }

    /**
     * Gets the attribute value for BasicSalary, using the alias name BasicSalary.
     * @return the value of BasicSalary
     */
    public BigDecimal getBasicSalary() {
        return (BigDecimal) getAttributeInternal(BASICSALARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BasicSalary.
     * @param value value to set the BasicSalary
     */
    public void setBasicSalary(BigDecimal value) {
        setAttributeInternal(BASICSALARY, value);
    }

    /**
     * Gets the attribute value for SocialAllowance, using the alias name SocialAllowance.
     * @return the value of SocialAllowance
     */
    public BigDecimal getSocialAllowance() {
        return (BigDecimal) getAttributeInternal(SOCIALALLOWANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SocialAllowance.
     * @param value value to set the SocialAllowance
     */
    public void setSocialAllowance(BigDecimal value) {
        setAttributeInternal(SOCIALALLOWANCE, value);
    }

    /**
     * Gets the attribute value for TransportAllowance, using the alias name TransportAllowance.
     * @return the value of TransportAllowance
     */
    public BigDecimal getTransportAllowance() {
        return (BigDecimal) getAttributeInternal(TRANSPORTALLOWANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransportAllowance.
     * @param value value to set the TransportAllowance
     */
    public void setTransportAllowance(BigDecimal value) {
        setAttributeInternal(TRANSPORTALLOWANCE, value);
    }

    /**
     * Gets the attribute value for WorkNatureAllowance, using the alias name WorkNatureAllowance.
     * @return the value of WorkNatureAllowance
     */
    public BigDecimal getWorkNatureAllowance() {
        return (BigDecimal) getAttributeInternal(WORKNATUREALLOWANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkNatureAllowance.
     * @param value value to set the WorkNatureAllowance
     */
    public void setWorkNatureAllowance(BigDecimal value) {
        setAttributeInternal(WORKNATUREALLOWANCE, value);
    }

    /**
     * Gets the attribute value for HousingAllowance, using the alias name HousingAllowance.
     * @return the value of HousingAllowance
     */
    public BigDecimal getHousingAllowance() {
        return (BigDecimal) getAttributeInternal(HOUSINGALLOWANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HousingAllowance.
     * @param value value to set the HousingAllowance
     */
    public void setHousingAllowance(BigDecimal value) {
        setAttributeInternal(HOUSINGALLOWANCE, value);
    }

    /**
     * Gets the attribute value for OtherAllowance, using the alias name OtherAllowance.
     * @return the value of OtherAllowance
     */
    public BigDecimal getOtherAllowance() {
        return (BigDecimal) getAttributeInternal(OTHERALLOWANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherAllowance.
     * @param value value to set the OtherAllowance
     */
    public void setOtherAllowance(BigDecimal value) {
        setAttributeInternal(OTHERALLOWANCE, value);
    }

    /**
     * Gets the attribute value for TotalMonthlySalary, using the alias name TotalMonthlySalary.
     * @return the value of TotalMonthlySalary
     */
    public BigDecimal getTotalMonthlySalary() {
        return (BigDecimal) getAttributeInternal(TOTALMONTHLYSALARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalMonthlySalary.
     * @param value value to set the TotalMonthlySalary
     */
    public void setTotalMonthlySalary(BigDecimal value) {
        setAttributeInternal(TOTALMONTHLYSALARY, value);
    }

    /**
     * Gets the attribute value for HousingType, using the alias name HousingType.
     * @return the value of HousingType
     */
    public String getHousingType() {
        return (String) getAttributeInternal(HOUSINGTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HousingType.
     * @param value value to set the HousingType
     */
    public void setHousingType(String value) {
        setAttributeInternal(HOUSINGTYPE, value);
    }

    /**
     * Gets the attribute value for AdditionalNotes, using the alias name AdditionalNotes.
     * @return the value of AdditionalNotes
     */
    public String getAdditionalNotes() {
        return (String) getAttributeInternal(ADDITIONALNOTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdditionalNotes.
     * @param value value to set the AdditionalNotes
     */
    public void setAdditionalNotes(String value) {
        setAttributeInternal(ADDITIONALNOTES, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.WorkerDraft");
    }
}

