package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 21 11:57:30 AST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorkerViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WorkerViewImpl() {
    }
}

